### ISSUE TITLE
adding to env:

### ISSUE THREAD

**Issue by jc36** [ReDev1L/helm-env-file-parsing#1]
How do you then insert the values of these secrets in the "env:" in the deployment? List each for example like this: (?)
```
          env:          
          - name: "USERNAME"
            valueFrom:
              secretKeyRef:
                key:  username
                name: {{ .Release.Name }}-auth
          - name: "PASSWORD"
            valueFrom:
              secretKeyRef:
                key:  password
                name: {{ .Release.Name }}-auth
```

**Comment by ReDev1L** [comment]
```apiVersion: v1
kind: Secret
metadata:
  name: php-fpm-{{ .Values.environment }}-env
  labels:
    app.kubernetes.io/name: {{ include "helm.fullname" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    project: {{ include "helm.name" . }}
    environment: {{ .Values.environment }}
type: Opaque
data:
{{ tuple . ".backendenv" | include "env.parseFile" | indent 2 | trimSuffix "\n" }}
```

**Comment by jc36** [comment]
I added another helper to use it in the deployment template
```
{{/*
Function to parse .env file and output in yaml
KEY_ENV1=VAL_ENV1  =>  - name: "KEY_ENV1"
                         valueFrom:
                           secretKeyRef:
                             key:  KEY_ENV1
                             name: {{ template "chart.fullname" $scope }}-env


Usage:
{{ tuple . ".env-production"  | include "env.parseFile2" | indent 2}}

*/}}
{{- define "env.parseFile2" -}}
{{- $scope := index . 0 -}}
{{- $filePath := index . 1 -}}
{{- range $scope.Files.Lines $filePath -}}
{{- $a := splitn "=" 2 . -}}
{{- if $a._0 -}}
- name: {{ $a._0 }}
  valueFrom:
    secretKeyRef:
      key:  {{ $a._0 }}
      name: {{ template "chart.fullname" $scope }}-env
{{ end -}}
{{- end -}}
{{- end -}}
```

**Comment by ReDev1L** [comment]
nice, but thats very customized, i'm using like that:
```
      containers:
      - name: php-fpm
        image: "{{ .Values.app.deployment.images.php.repository }}:{{ .Values.app.deployment.images.php.tag }}"
        imagePullPolicy: {{ .Values.app.deployment.images.php.pullPolicy }}
        envFrom:
          - secretRef:
              name: php-fpm-{{ .Values.environment }}-env
```
pulling full secret with one key
